spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_leaf?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: dong
    password: dong@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false